FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    curl \
    samtools \
    unzip \
    default-jre \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask requests tqdm

WORKDIR /app

COPY . /app/

CMD ["python", "downloader_api.py"] 