FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    curl \
    samtools \
    unzip \
    default-jre \
    && rm -rf /var/lib/apt/lists/*

# Install GATK
WORKDIR /usr/local
RUN wget -q https://github.com/broadinstitute/gatk/releases/download/4.4.0.0/gatk-4.4.0.0.zip && \
    unzip gatk-4.4.0.0.zip && \
    rm gatk-4.4.0.0.zip && \
    ln -s /usr/local/gatk-4.4.0.0/gatk /usr/local/bin/gatk

RUN pip install flask requests tqdm

WORKDIR /app

COPY . /app/

CMD ["python", "downloader_api.py"] 