"""23andMe and AncestryDNA exports are recognised by name and refused by decision.

Two separate defects are closed here.

**AncestryDNA was never detected.** ``FileType.ANCESTRY_DNA`` existed in
``app/api/models.py`` but ``_detect_file_type`` only ever looked for the string
``23andMe``, so an AncestryDNA export fell through every sniff and was refused as
"Unrecognized file format: unknown" -- a file we can name exactly, and measure,
reported as unrecognisable. The discriminator between the two is structural
rather than lexical: AncestryDNA's column-header row is uncommented, 23andMe's is
a ``#`` comment. It cannot be the field list, because 23andMe ships both a 4-column
``genotype`` layout and a 5-column ``allele1``/``allele2`` one, and the second is
spelled exactly like AncestryDNA's.

**The 23andMe refusal gave the wrong reason.** It said the files "must be
converted to VCF first, and that conversion is not implemented yet", which
promises the feature by describing its absence -- and misnames the problem
besides. The coordinates in these files are fine (build 37, plus strand, real
positions) and ``bcftools convert --tsv2vcf`` would produce a VCF happily.

What is actually wrong is downstream. PharmCAT alone degrades honestly: a
position it cannot see is a no-call. **ZaroPGx does not run PharmCAT alone.**
``pipelines/pgx/main.nf`` concatenates PyPGx's output into
``combined_outside.tsv`` and posts it as PharmCAT's ``outside_tsv``, and an
outside call overrides a no-call. PyPGx's own maintainer on array input
(pypgx#142): missing loci "will be falsely treated as homozygous reference even
though there might be variants". So a 23andMe v5 file, which carries no
``rs3892097``, yields ``CYP2D6 *1/*1`` and the report tells a ``*4/*4`` poor
metaboliser they metabolise codeine and tamoxifen normally.

Measured coverage of PharmCAT's 1,226 positions (2026-08-31, from each vendor's
published manifest -- a union of every chip revision, so an upper bound): 23andMe
v5 229 (18.7%), of which 222 SNVs; AncestryDNA v2 380 (31.0%). Of the 157 CYP2D6
positions: 25 and 14 respectively.
"""

import uuid

import pytest

from app.api.models import FileType
from app.api.routes.upload_router import _unanalysable_upload_reason
from app.api.utils.file_processor import FileAnalysis, FileProcessor

TWENTYTHREE_AND_ME = (
    "# This data file generated by 23andMe at: Sun Jan  1 00:00:00 2023\n"
    "# This file contains raw genotype data, including data that is not used in "
    "23andMe reports.\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
    "rs4477212\t1\t82154\tAA\n"
    "rs3094315\t1\t752566\tAG\n"
)

# The other layout 23andMe ships. Same column names AncestryDNA uses, so only the
# leading `#` tells them apart.
TWENTYTHREE_AND_ME_FIVE_COLUMN = (
    "# This data file generated by 23andMe at: Sun Jan  1 00:00:00 2023\n"
    "# rsid\tchromosome\tposition\tallele1\tallele2\n"
    "rs4477212\t1\t82154\tA\tA\n"
)

ANCESTRY_DNA = (
    "#AncestryDNA raw data download\n"
    "#This file was generated by AncestryDNA at: 01/01/2023 00:00:00 UTC\n"
    "#Data was collected using AncestryDNA array version: V2.0\n"
    "rsid\tchromosome\tposition\tallele1\tallele2\n"
    "rs4477212\t1\t82154\tA\tA\n"
    "rs3094315\t1\t752566\tA\tG\n"
)


def _typed(tmp_path, name: str, text: str, newline: str = "\n") -> FileType:
    path = tmp_path / name
    path.write_bytes(text.replace("\n", newline).encode("utf-8"))
    return FileProcessor(temp_dir=str(tmp_path))._detect_file_type(path)


# --- detection ---------------------------------------------------------------


def test_a_23andme_export_is_typed_as_23andme(tmp_path):
    assert _typed(tmp_path, "genome.txt", TWENTYTHREE_AND_ME) == (
        FileType.TWENTYTHREE_AND_ME
    )


def test_an_ancestrydna_export_is_typed_as_ancestrydna(tmp_path):
    """It used to reach FileType.UNKNOWN and be told we did not recognise it."""
    assert _typed(tmp_path, "AncestryDNA.txt", ANCESTRY_DNA) == FileType.ANCESTRY_DNA


def test_23andme_files_arrive_with_crlf_line_endings(tmp_path):
    """They always do. Reading them in text mode is what makes that a non-issue."""
    assert _typed(tmp_path, "genome.txt", TWENTYTHREE_AND_ME, newline="\r\n") == (
        FileType.TWENTYTHREE_AND_ME
    )
    assert _typed(tmp_path, "AncestryDNA.txt", ANCESTRY_DNA, newline="\r\n") == (
        FileType.ANCESTRY_DNA
    )


def test_the_column_header_row_decides_when_the_banner_is_gone(tmp_path):
    """A spreadsheet round-trip strips the vendor banner. The `#` on the header
    row is then the only thing left that distinguishes the two formats -- the
    column names cannot, because 23andMe's 5-column layout uses AncestryDNA's."""
    stripped_23andme = "# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t1\tAA\n"
    stripped_ancestry = (
        "rsid\tchromosome\tposition\tallele1\tallele2\nrs1\t1\t1\tA\tA\n"
    )

    assert _typed(tmp_path, "a.txt", stripped_23andme) == FileType.TWENTYTHREE_AND_ME
    assert _typed(tmp_path, "b.txt", stripped_ancestry) == FileType.ANCESTRY_DNA


def test_the_five_column_23andme_layout_is_not_read_as_ancestrydna(tmp_path):
    assert _typed(tmp_path, "genome.txt", TWENTYTHREE_AND_ME_FIVE_COLUMN) == (
        FileType.TWENTYTHREE_AND_ME
    )


def test_an_unrelated_text_file_is_not_claimed_as_an_array(tmp_path):
    """The negative control: the sniff must not swallow every .txt upload."""
    assert _typed(tmp_path, "notes.txt", "hello\nworld\n") == FileType.UNKNOWN
    assert _typed(tmp_path, "t.csv", "a,b,c\n1,2,3\n") == FileType.UNKNOWN


def test_a_data_row_alone_says_nothing(tmp_path):
    """Both vendors write rsID/chrom/pos rows, so a headerless body is not
    evidence of either -- guessing would name a vendor we cannot see."""
    assert _typed(tmp_path, "rows.txt", "rs1\t1\t82154\tAA\n") == FileType.UNKNOWN


# --- refusal -----------------------------------------------------------------


ARRAY_TYPES = [FileType.TWENTYTHREE_AND_ME, FileType.ANCESTRY_DNA]


def _workflow_for(file_type: FileType) -> dict:
    workflow = FileProcessor(temp_dir="/tmp").determine_workflow(
        FileAnalysis(
            file_type=file_type,
            is_compressed=False,
            has_index=False,
            file_size=1,
            vcf_info=None,
            is_valid=True,
            validation_errors=[],
        )
    )
    workflow["file_type"] = file_type.value
    return workflow


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_an_array_upload_is_refused_by_the_gate(file_type):
    workflow = _workflow_for(file_type)

    assert workflow["unsupported"] is True
    assert workflow["is_provisional"] is False
    assert _unanalysable_upload_reason(workflow)


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_refusal_names_the_vendor_rather_than_calling_it_unrecognised(file_type):
    reason = _workflow_for(file_type)["unsupported_reason"]
    vendor = "23andMe" if file_type is FileType.TWENTYTHREE_AND_ME else "AncestryDNA"

    assert vendor in reason
    assert "Unrecognized" not in reason


@pytest.mark.parametrize(
    "file_type,positions,cyp2d6",
    [
        (FileType.TWENTYTHREE_AND_ME, "229", "25"),
        (FileType.ANCESTRY_DNA, "380", "14"),
    ],
)
def test_the_refusal_carries_the_measured_numbers(file_type, positions, cyp2d6):
    """Not "limited variant coverage" -- the counts, and the denominator."""
    reason = _workflow_for(file_type)["unsupported_reason"]

    assert positions in reason
    assert "1,226" in reason
    assert cyp2d6 in reason
    assert "157" in reason


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_refusal_states_the_failure_mode_not_just_the_coverage(file_type):
    """Low coverage alone would argue for an incomplete report, which is a thing
    a user might reasonably still want. The argument for refusing is that the
    report would be confidently wrong instead."""
    reason = _workflow_for(file_type)["unsupported_reason"].lower()

    assert "pypgx" in reason
    assert "homozygous reference" in reason
    assert "no-call" in reason
    assert "cyp2d6" in reason


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_refusal_is_stated_as_a_decision_and_not_as_pending_work(file_type):
    strings = _workflow_for(file_type)["recommendations"]
    strings += _workflow_for(file_type)["warnings"]
    strings.append(_workflow_for(file_type)["unsupported_reason"])

    for text in strings:
        lowered = text.lower()
        for promise in (
            "not implemented",
            "not yet implemented",
            "in development",
            "once conversion exists",
            "(to do)",
            "coming soon",
        ):
            assert promise not in lowered, text


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_copy_says_chips_cannot_see_structural_variants_at_all(file_type):
    """The half of the gap no amount of chip density would close."""
    warnings = " ".join(_workflow_for(file_type)["warnings"]).lower()

    assert "duplications" in warnings
    assert "deletions" in warnings


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_copy_quotes_pharmcats_own_position(file_type):
    recs = " ".join(_workflow_for(file_type)["recommendations"])

    assert "not very useful reports" in recs
    assert "PharmCAT" in recs


@pytest.mark.parametrize("file_type", ARRAY_TYPES)
def test_the_copy_names_the_inputs_to_upload_instead(file_type):
    reason = _workflow_for(file_type)["unsupported_reason"].lower()

    for accepted in ("vcf", "bam", "cram", "sam"):
        assert accepted in reason


def test_only_23andme_names_variants_we_actually_audited():
    """AncestryDNA's per-variant absences were never audited, so its copy gives
    counts and stops. Naming variants we have not checked for would be the same
    kind of confident-sounding invention the refusal exists to prevent."""
    twentythree = " ".join(_workflow_for(FileType.TWENTYTHREE_AND_ME)["warnings"])
    ancestry = " ".join(_workflow_for(FileType.ANCESTRY_DNA)["warnings"])

    assert "rs3892097" in twentythree
    assert "rs1065852" in twentythree
    assert "rs3892097" not in ancestry
    # The two that ARE absent from every vendor and version are said for both.
    for text in (twentythree, ancestry):
        assert "rs35742686" in text
        assert "rs3064744" in text


# --- end to end through the real endpoint ------------------------------------


@pytest.fixture
def upload(client, monkeypatch, tmp_path):
    """POST real bytes at the real endpoint, through the real FileProcessor."""
    from app.api.routes import upload_router

    monkeypatch.setattr(upload_router.file_processor, "temp_dir", tmp_path / "uploads")

    created_patients = []
    monkeypatch.setattr(
        upload_router,
        "create_patient",
        lambda db, identifier: (created_patients.append(identifier) or uuid.uuid4()),
    )
    monkeypatch.setattr(
        upload_router,
        "register_genetic_data",
        lambda db, patient_id, file_type, file_path, is_supplementary: uuid.uuid4(),
    )

    # Patched for the same reason test_upload_story_coherence patches them: a
    # refusal happens before either is reached, and a test that only passes
    # because the refusal fired would look identical to one that reached them.
    class _FakeJob:
        def __init__(self):
            self.id = uuid.uuid4()
            self.status = "pending"
            self.job_metadata = {}

    class _FakeJobService:
        def __init__(self, db):
            self.job = _FakeJob()

        def create_job(self, job_create):
            return self.job

        def update_job(self, job_id, job_update):
            return self.job

    monkeypatch.setattr(upload_router, "JobService", _FakeJobService)

    async def _noop_background(*args, **kwargs):
        return None

    monkeypatch.setattr(
        upload_router, "process_file_nextflow_background_with_db", _noop_background
    )

    def _post(name, text):
        return client.post(
            "/upload/genomic-data",
            files=[("files", (name, text.encode("utf-8"), "text/plain"))],
            data={"reference_genome": "hg38"},
        )

    _post.created_patients = created_patients
    return _post


def test_an_ancestrydna_upload_is_refused_before_a_job_exists(upload):
    resp = upload("AncestryDNA.txt", ANCESTRY_DNA)

    assert resp.status_code == 400, resp.text
    detail = resp.json()["detail"]
    assert "AncestryDNA" in detail
    assert "Unrecognized file format" not in detail
    assert upload.created_patients == []


def test_an_ancestrydna_preview_reaches_the_same_verdict(client):
    """The header preview must not draw a plan the upload would then refuse."""
    resp = client.post(
        "/upload/inspect-header",
        files={"file": ("AncestryDNA.txt", ANCESTRY_DNA.encode("utf-8"), "text/plain")},
    )

    assert resp.status_code == 200, resp.text
    workflow = resp.json()["compat"]["workflow"]
    assert workflow["refused"] is True
    assert "AncestryDNA" in (workflow["refusal_reason"] or "")
    assert workflow["needs_conversion"] is False
